import { Inter } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { ThemeProvider } from 'next-themes';
import "./globals.css";
import "../css/style.css";
import "../css/icon.css";
import "../css/swiper-bundle.min.css";
import "../css/aboutus.css";


import Footer from "@/components-root/Footer";
import Navbar from "@/components-root/Navbar";
import BackToTop from "@/components-root/BackToTop";
import dynamic from "next/dynamic";


const DynamicMainComponent = dynamic(() => import("@/components-root/MainComponent"), {
  ssr: false,
  loading: () => <p>Loading...</p>
});

const inter = Inter({ subsets: ["latin"] });
const playfair_display = Playfair_Display({ 
  subsets: ["latin"],
  variable: '--font-playfair_display',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet" />
        <script src="//code.jivosite.com/widget/uOTObb4fce" async></script>
        <title>JKtravels</title>
      </head>
      <UserProvider>
        <body className={playfair_display.variable} suppressHydrationWarning={true}>
          <ThemeProvider attribute="class">
            <Navbar />
            {children}
            <Footer />
            <BackToTop />
            <DynamicMainComponent />
          </ThemeProvider>
        </body>
      </UserProvider>
    </html>
  );
}
